apiVersion: app/v1
kind: Deployment
metadata:
  name: kubedemoapp-deployment
spec: 
  replicas: 4
  selector:
    matchLabels:
      app: kubedemoapp
  template:
    metadata:
      labels:
        app: kubedemoapp 
    spec: 
      containers:
        - name: kubedemoapp
          image: satya1306/gowri62:week9
          ports:
            - containerPort: 5000